--- 
baseurl: /erkahn.github.io
description: ""
exclude: 
  - Gemfile
  - Gemfile.lock
gems: 
  - jekyll-feed
github_username: erkahn
markdown: kramdown
theme: minima
title: "Hakan Erkan Kişisel Bloğu"
url: "https://erkahn.github.io/"